name: Build Resource Pack

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip Resource Pack
        run: zip -r ${{ github.event.repository.name }}.zip .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}.zip
          tag_name: latest
          name: Latest Release
          body: "Automagic resources build"
